### ISSUE TITLE
Choose song for robot reveal

### ISSUE THREAD

**Issue by vichik123** [Galaxia5987/robot-2024#36]
We, the programming team, mind and soul of the robot believe in brotherhood.

I say we band against the rest of the team and choose a song that we like!
The less songs the more chance our song is picked, and if we band together we secure more initial votes.

Add your song suggestions to this issue, and together we will overrule our team's democracy!

**Comment by GaiaZano05** [comment]
Viva la revolución

**Comment by Emma03L** [comment]
Great Balls Of Fire

**Comment by vichik123** [comment]
> Viva la revolución

Not a song....
