### ISSUE TITLE
AdvantageScope layout file is in wrong format 

### ISSUE THREAD

**Issue by katzuv** [Galaxia5987/robot-2024#56]
[This](https://github.com/Galaxia5987/robot-2024/blob/58cf38f5b46718e99a2f38ea5db6fa4906baec8e/important-files/advantage-scope/cad/Robot_Classified/full_robot_layout.json) is the file I tried to import.
![image](https://github.com/Galaxia5987/robot-2024/assets/31829093/4a4d809a-105e-4cb4-a18b-3733b47d0c98)
Probably broke after AdvantageScope v3.1.0 was released.

**Comment by rakrakon** [comment]
https://github.com/Galaxia5987/robot-2024/pull/57#issue-2133843465

**Comment by katzuv** [comment]
I think this will be automatically merged only when the code is merged to main. Closing for now
